In [1]:
import numpy as np

In [8]:
arr = np.array([10,20,30,40,50])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

[10 20 30 40 50]
(5,)
5
1
int64


In [12]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2


In [23]:
arr = np.arange(1, 21)
print(arr)
print(arr.dtype)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
int64


In [25]:
arr = np.array([10,20,30,40,50])
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[10. 20. 30. 40. 50.]
float64


In [22]:
import numpy as np

arr = np.array([[10, 20, 30],
                [40, 50, 60]])

print(arr.shape)
print(arr.size)
print(arr.ndim)

(2, 3)
6
2


In [28]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [30]:
arr = np.ones((4,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [32]:
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [57]:
arr = np.linspace(0,1,(11))
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [95]:
arr = np.random.randint(1,101,10)
arr

array([27,  6, 95, 70, 57, 37, 55, 34, 65, 80], dtype=int32)

In [107]:
arr = np.random.randint(10,51,(3,4))
arr

array([[19, 17, 47, 14],
       [16, 17, 13, 48],
       [18, 29, 41, 15]], dtype=int32)

In [61]:
arr = np.arange(1,21).reshape(2,10)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [63]:
arr = np.linspace(2,2.5,(55))
arr

array([2.        , 2.00925926, 2.01851852, 2.02777778, 2.03703704,
       2.0462963 , 2.05555556, 2.06481481, 2.07407407, 2.08333333,
       2.09259259, 2.10185185, 2.11111111, 2.12037037, 2.12962963,
       2.13888889, 2.14814815, 2.15740741, 2.16666667, 2.17592593,
       2.18518519, 2.19444444, 2.2037037 , 2.21296296, 2.22222222,
       2.23148148, 2.24074074, 2.25      , 2.25925926, 2.26851852,
       2.27777778, 2.28703704, 2.2962963 , 2.30555556, 2.31481481,
       2.32407407, 2.33333333, 2.34259259, 2.35185185, 2.36111111,
       2.37037037, 2.37962963, 2.38888889, 2.39814815, 2.40740741,
       2.41666667, 2.42592593, 2.43518519, 2.44444444, 2.4537037 ,
       2.46296296, 2.47222222, 2.48148148, 2.49074074, 2.5       ])

In [65]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
arr = np.random.randint(0,2,(100))
print(arr)
print(arr.mean())
print(arr.min())
print(arr.max())
print(arr.std())

[1 1 0 1 1 0 1 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 1 1 0 0 1 0 0 0 1 1 0 0 1
 0 0 0 1 0 1 1 1 0 1 0 0 1 1 1 0 0 1 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 1 0 1 0
 0 1 1 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 0 0 0 1 0 0]
0.47
0
1
0.49909918853871116


In [108]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

In [109]:
arr[0]

np.int64(10)

In [110]:
arr[-1]

np.int64(80)

In [112]:
arr[2:5]

array([30, 40, 50])

In [128]:
arr[0:8:2]

array([10, 30, 50, 70])

In [130]:
arr[::-1]

array([80, 70, 60, 50, 40, 30, 20, 10])

In [131]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [133]:
arr[1][1]

np.int64(50)

In [134]:
arr[0]

array([10, 20, 30])

In [152]:
arr[:,2]

array([30, 60, 90])

In [154]:
arr[0:2,1:]

array([[20, 30],
       [50, 60]])

In [156]:
arr[1:3,0:2]

array([[40, 50],
       [70, 80]])

In [159]:
arr[0,2]
arr[1,2]
arr[2,2]

np.int64(90)

In [168]:
arr[0:2,0:1]

array([[10],
       [40]])

In [169]:
arr[0:2,1:2]

array([[20],
       [50]])

In [171]:
arr[0,0:2]

array([10, 20])

In [173]:
arr[1,0:2]

array([40, 50])

In [174]:
print(arr[1])
print(arr[1, :])
print(arr[:, 1])

[40 50 60]
[40 50 60]
[20 50 80]


In [176]:
arr[:,2]

array([30, 60, 90])

In [177]:
arr = np.array([12, 67, 34, 89, 45, 91, 23, 76])

In [178]:
arr[arr>50]

array([67, 89, 91, 76])

In [179]:
arr = np.array([11, 24, 37, 42, 55, 68, 73, 80, 91])

In [180]:
arr[arr%2==0]

array([24, 42, 68, 80])

In [181]:
import numpy as np

arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [183]:
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [184]:
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [185]:
arr = np.arange(1,13).reshape(6,2)
arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [186]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [195]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [194]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [196]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [198]:
arr.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [204]:
arr = np.arange(1,7).reshape(2,3)
print(arr)
print(arr.T)
print(arr.transpose())

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [208]:
arr = np.arange(1, 25).reshape(4,6)
print(arr)
arr.T

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


array([[ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23],
       [ 6, 12, 18, 24]])

In [218]:
arr = np.arange(1,17).reshape(4,4)
print(arr)
arr = arr.T
print('\n',arr)
print('\n',arr.flatten())
print('\n',arr.reshape(2,8))
print("\n",arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]

 [ 1  5  9 13  2  6 10 14  3  7 11 15  4  8 12 16]

 [[ 1  5  9 13  2  6 10 14]
 [ 3  7 11 15  4  8 12 16]]

 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [221]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [229]:
result = np.concatenate((a,b))
result

array([1, 2, 3, 4, 5, 6])

In [230]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

In [238]:
r = np.concatenate((a,b),axis=0)
r

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [239]:
r = np.concatenate((a,b),axis=1)
r

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [240]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [243]:
r = np.vstack((a,b))
r

array([[1, 2, 3],
       [4, 5, 6]])

In [246]:
r = np.hstack((a,b))
r

array([1, 2, 3, 4, 5, 6])

In [254]:
print(np.vstack((a,b)))
print(np.concatenate((a,b), axis=0))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [255]:
np.hstack((a,b))
np.concatenate((a,b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [266]:
arr = np.array([10, 20, 30, 40, 50, 60])

In [267]:
print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [269]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.split(arr,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [271]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

np.split(arr,2,axis=1)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [277]:
X = np.array([
    [10, 20],
    [30, 40],
    [50, 60],
    [70, 80]
])

In [278]:
new_data = np.array([
    [90, 100],
    [110, 120]
])

In [282]:
r = np.concatenate((X,new_data),axis=0)

In [283]:
r.shape

(6, 2)

In [297]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.array([5, 6])

In [286]:
r = np.hstack((a,b,c))
r

array([1, 2, 3, 4, 5, 6])

In [298]:
r = np.concatenate((a,b,c),axis=0)
r

array([1, 2, 3, 4, 5, 6])