In [1]:
import numpy as np

In [2]:
marks = np.array([
    [78, 85, 92],
    [65, 70, 80],
    [90, 95, 88],
    [55, 60, 68],
    [82, 76, 91]
])

In [3]:
marks.mean()

np.float64(78.33333333333333)

In [4]:
marks.mean(axis=1)

array([85.        , 71.66666667, 91.        , 61.        , 83.        ])

In [5]:
marks.mean(axis=0)

array([74. , 77.2, 83.8])

In [6]:
marks.max()

np.int64(95)

In [7]:
marks.min()

np.int64(55)

In [29]:
marks.mean(axis=1).argmax()

np.int64(2)

In [30]:
marks[2]

array([90, 95, 88])

In [15]:
t_i = marks[2:3]
t_i

array([[90, 95, 88]])

In [19]:
t_i.mean()

np.float64(91.0)

In [23]:
g_80=marks[marks>=80]
g_80

array([85, 92, 80, 90, 95, 88, 82, 91])

In [26]:
np.count_nonzero(g_80)

np.int64(8)

In [31]:
np.where(marks>=80)[0]

array([0, 0, 1, 2, 2, 2, 4, 4])

In [32]:
data = np.array([10, 20, 30, 40, 50])

In [33]:
normalized = (data - data.min()) / (data.max() - data.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [35]:
z = (data - data.mean()) / data.std()
z

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [36]:
z.mean()

np.float64(0.0)

In [37]:
z.std()

np.float64(0.9999999999999999)

In [38]:
X = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400]
])

In [42]:
scale = np.array([0.1,0.01])

In [44]:
r = X*scale
r

array([[1., 1.],
       [2., 2.],
       [3., 3.],
       [4., 4.]])

In [45]:
X = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

In [47]:
c = np.mean(X,axis=0)

In [48]:
r = X-c

In [49]:
r

array([[-10., -10., -10.],
       [  0.,   0.,   0.],
       [ 10.,  10.,  10.]])

In [50]:
data = np.arange(1, 21)

In [53]:
train = data[:16]
test = data[16:]
train


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [54]:
test

array([17, 18, 19, 20])

In [55]:
np.random.seed(42)

data = np.random.randint(1, 101, 20)

In [57]:
data.mean()

np.float64(54.1)

In [59]:
np.median(data)

np.float64(57.0)

In [60]:
np.std(data)

np.float64(31.472051092993606)

In [65]:
h = np.sort(data)[-3:][::-1]
h

array([100,  93,  88], dtype=int32)

In [67]:
l = np.sort(data)[:3]
l

array([ 2,  3, 15], dtype=int32)

In [69]:
f = data[data>=50]
f

array([ 52,  53,  61,  72,  75,  75,  83,  87,  88,  88,  93, 100],
      dtype=int32)

In [70]:
np.count_nonzero(f)

np.int64(12)

In [71]:
students = np.array(["A", "B", "C", "D", "E", "F"])

marks = np.array([82, 67, 95, 74, 88, 91])

In [75]:
t_n = np.argmax(marks)
students[t_n]

np.str_('C')

In [77]:
t_3 = np.argsort(marks)[-3:][::-1]
students[t_3]

array(['C', 'F', 'E'], dtype='<U1')

In [80]:
d = np.argsort(marks)[::-1]
students[d]

array(['C', 'F', 'E', 'A', 'D', 'B'], dtype='<U1')

In [88]:
g_80 = students[marks>=80]
g_80

array(['A', 'C', 'E', 'F'], dtype='<U1')

In [89]:
c = np.count_nonzero(marks>=80)
c

np.int64(4)

In [90]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

In [91]:
A+B

array([[ 6,  8],
       [10, 12]])

In [92]:
A-B

array([[-4, -4],
       [-4, -4]])

In [93]:
A*B

array([[ 5, 12],
       [21, 32]])

In [94]:
A@B

array([[19, 22],
       [43, 50]])

In [95]:
image = np.array([
    [10, 20, 30],
    [40, 250, 60],
    [70, 80, 255]
])

In [96]:
image[image>=200]

array([250, 255])

In [97]:
np.count_nonzero(image>=200)

np.int64(2)

In [99]:
normalized = (image - image.min()) / (image.max() - image.min())
normalized

array([[0.        , 0.04081633, 0.08163265],
       [0.12244898, 0.97959184, 0.20408163],
       [0.24489796, 0.28571429, 1.        ]])

In [100]:
normalized.shape

(3, 3)

In [101]:
students = np.array([
    [101, 78, 85, 92],
    [102, 65, 70, 80],
    [103, 90, 95, 88],
    [104, 55, 60, 68],
    [105, 82, 76, 91]
])

In [104]:
s = students[:,:1]
s

array([[101],
       [102],
       [103],
       [104],
       [105]])

In [108]:
marks = students[:,1:]
marks

array([[78, 85, 92],
       [65, 70, 80],
       [90, 95, 88],
       [55, 60, 68],
       [82, 76, 91]])

In [110]:
s_a = np.mean(marks,axis=1)
s_a

array([85.        , 71.66666667, 91.        , 61.        , 83.        ])

In [111]:
sub_avg = np.mean(marks,axis = 0)
sub_avg

array([74. , 77.2, 83.8])

In [114]:
ids = students[:,0]
topper_inx = np.argmax(s_a)
topper_id = ids[topper_inx]
topper_id

np.int64(103)

In [115]:
marks.max()

np.int64(95)

In [116]:
ids = students[:, 0]
marks = students[:, 1:]

student_avg = marks.mean(axis=1)
subject_avg = marks.mean(axis=0)

topper_index = np.argmax(student_avg)
topper_id = ids[topper_index]
topper_marks = marks[topper_index]

above_80 = students[student_avg >= 80]

lowest_index = np.argmin(student_avg)
lowest_student = students[lowest_index]

order = np.argsort(student_avg)[::-1]
sorted_students = students[order]

In [117]:
np.random.seed(10)

X = np.random.randint(10, 101, (10, 4))

In [119]:
X

array([[19, 25, 74, 38],
       [99, 39, 18, 83],
       [10, 50, 46, 26],
       [21, 64, 98, 72],
       [43, 82, 88, 59],
       [61, 64, 87, 79],
       [23, 35, 23, 96],
       [40, 40, 99, 22],
       [75, 41, 67, 46],
       [37, 28, 87, 32]], dtype=int32)

In [118]:
X.shape

(10, 4)

In [120]:
np.argmax(X)

np.int64(4)

In [121]:
X.max()

np.int32(99)