In [13]:
import numpy as np

In [14]:
arr = np.array([10, 20, 30, 40, 50])

In [15]:
arr.sum()

np.int64(150)

In [16]:
arr.mean()

np.float64(30.0)

In [17]:
arr.min()

np.int64(10)

In [18]:
arr.max()

np.int64(50)

In [19]:
np.median(arr)

np.float64(30.0)

In [20]:
arr.std()

np.float64(14.142135623730951)

In [21]:
arr.var()

np.float64(200.0)

In [22]:
arr.std()

np.float64(14.142135623730951)

In [23]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [24]:
arr.sum()


np.int64(450)

In [25]:
arr.mean()


np.float64(50.0)

In [26]:
arr.min()


np.int64(10)

In [27]:
arr.max()

np.int64(90)

In [28]:
arr.mean(axis=0)

array([40., 50., 60.])

In [29]:
arr.mean(axis=1)

array([20., 50., 80.])

In [30]:
arr.sum(axis=0)

array([120, 150, 180])

In [31]:
arr.sum(axis=1)

array([ 60, 150, 240])

In [32]:
marks = np.array([
    [80, 75, 90],
    [60, 85, 70],
    [95, 90, 88],
    [50, 65, 72]
])

In [34]:
marks.mean(axis=1)

array([81.66666667, 71.66666667, 91.        , 62.33333333])

In [35]:
marks.mean(axis=0)

array([71.25, 78.75, 80.  ])

In [36]:
marks = np.array([65, 89, 72, 95, 81, 78])

In [38]:
marks.max()


np.int64(95)

In [39]:
marks.min()


np.int64(65)

In [40]:
np.argmax(marks)


np.int64(3)

In [41]:
np.argmin(marks)

np.int64(0)

In [42]:
marks = np.array([
    [80, 75, 90],
    [60, 85, 70],
    [95, 90, 88]
])

In [43]:
np.argmax(marks)

np.int64(6)

In [44]:
np.unravel_index(np.argmax(marks), marks.shape)

(np.int64(2), np.int64(0))

In [45]:
data = np.array([12, 15, 18, 21, 24, 27, 30])

In [46]:
data.mean()

np.float64(21.0)

In [48]:
np.median(data)

np.float64(21.0)

In [49]:
data.var()

np.float64(36.0)

In [50]:
data.std()

np.float64(6.0)

In [51]:
data.min()

np.int64(12)

In [52]:
data.max()

np.int64(30)

In [53]:
scores = np.array([
    [80, 90, 70],
    [60, 75, 85],
    [95, 88, 92],
    [55, 65, 60]
])

In [60]:
student_avg = scores.mean(axis=1)

In [55]:
scores.mean(axis=0)

array([72.5 , 79.5 , 76.75])

In [57]:
scores.mean()

np.float64(76.25)

In [58]:
scores.max()

np.int64(95)

In [59]:
scores.min()

np.int64(55)

In [62]:
student_avg

array([80.        , 73.33333333, 91.66666667, 60.        ])

In [63]:
np.argmax(student_avg)+1

np.int64(3)

In [78]:
import numpy as np

arr = np.array([10, 25, 30, 45, 50, 65, 70])

In [79]:
marks = arr>40

In [80]:
marks

array([False, False, False,  True,  True,  True,  True])

In [81]:
marks_value = arr[arr>40]
marks_value

array([45, 50, 65, 70])

In [82]:
even_marks = arr[arr%2==0]
even_marks

array([10, 30, 50, 70])

In [89]:
v = arr[(arr>20) & (arr<60)]
v

array([25, 30, 45, 50])

In [91]:
va = arr[(arr<30) | (arr>60)]
va


array([10, 25, 65, 70])

In [92]:
marks = np.array([35, 78, 45, 92, 28, 66])

In [93]:
np.where(marks>=50,'Pass','Fail')

array(['Fail', 'Pass', 'Fail', 'Pass', 'Fail', 'Pass'], dtype='<U4')

In [94]:
np.where(marks>=50, marks,0)

array([ 0, 78,  0, 92,  0, 66])

In [95]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

In [97]:
data[data>50]

array([60, 70, 80, 90])

In [98]:
students = np.array([
    [101, 85],
    [102, 45],
    [103, 92],
    [104, 67],
    [105, 38]
])

In [109]:
students[students[:, 1]>60]

array([[101,  85],
       [103,  92],
       [104,  67]])

In [113]:
students[(students[:,1]>50) & (students[:,1]<90)]

array([[101,  85],
       [104,  67]])

In [114]:
arr = np.array([10, 25, 40, 55, 70, 85])

In [116]:
np.where(arr>40)[0]

array([3, 4, 5])

In [118]:
prices = np.array([120, 450, 80, 999, 250, 60, 700])

In [119]:
prices[prices>200]

array([450, 999, 250, 700])

In [120]:
prices[prices>100]

array([120, 450, 999, 250, 700])

In [121]:
prices[(prices>=100) & (prices<=700)]

array([120, 450, 250, 700])

In [124]:
np.sort(prices)[-3:][::-1]

array([999, 700, 450])

In [125]:
data = np.array([
    [1, 25],
    [2, 67],
    [3, 45],
    [4, 89],
    [5, 32]
])

In [136]:
data[data[:,1]>=50]

array([[ 2, 67],
       [ 4, 89]])

In [130]:
data[data[:,1]<50]

array([[ 1, 25],
       [ 3, 45],
       [ 5, 32]])

In [142]:
data[data[:,1] >= 50,0]

array([2, 4])

In [143]:
import numpy as np

arr = np.array([10, 20, 30, 40])

In [144]:
arr + 5

array([15, 25, 35, 45])

In [145]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [146]:
a+b


array([11, 22, 33])

In [147]:
a*b

array([10, 40, 90])

In [149]:
a**2

array([1, 4, 9])

In [150]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [151]:
a + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [152]:
a = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

b = np.array([1, 2, 3])

In [153]:
a+b

array([[11, 22, 33],
       [41, 52, 63]])

In [165]:
np.ones((3,4)) + np.ones((1,4))

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [158]:
np.ones((3,4)) + np.ones((3,))

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [159]:
np.ones((3,4)) + np.ones((3,1))

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [160]:
np.ones((2,3)) + np.ones((4,3))

ValueError: operands could not be broadcast together with shapes (2,3) (4,3) 

In [166]:
marks = np.array([40, 50, 60, 70, 80])

In [167]:
r = marks +5

In [168]:
r

array([45, 55, 65, 75, 85])

In [170]:
p = (marks/100)*100
p

array([40., 50., 60., 70., 80.])

In [171]:
a = np.array([
    [1, 2],
    [3, 4]
])

b = np.array([
    [5, 6],
    [7, 8]
])

In [173]:
a*b

array([[ 5, 12],
       [21, 32]])

In [174]:
a@b

array([[19, 22],
       [43, 50]])

In [175]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [176]:
features = np.array([
    [10, 20],
    [20, 30],
    [30, 40],
    [40, 50]
])

In [177]:

scale = np.array([0.1, 0.01])

In [178]:
features * scale

array([[1. , 0.2],
       [2. , 0.3],
       [3. , 0.4],
       [4. , 0.5]])

In [179]:
X = np.array([
    [10, 20, 30],
    [20, 30, 40],
    [30, 40, 50]
])

mean = X.mean(axis=0)
std = X.std(axis=0)

In [180]:
(X - mean) / std

array([[-1.22474487, -1.22474487, -1.22474487],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.22474487,  1.22474487,  1.22474487]])

In [181]:
import numpy as np

arr = np.random.randint(1, 101, 10)
print(arr)

[18 36 65 38 39 55 97 92 46 37]


In [187]:
arr = np.random.rand(100)
print(arr)

[0.03328537 0.58056717 0.40595887 0.2070066  0.7464391  0.95146778
 0.66953288 0.57801818 0.9568823  0.51944625 0.29451893 0.62084081
 0.06746107 0.72260445 0.89822124 0.25794382 0.05609806 0.07273942
 0.05497842 0.48023686 0.7167715  0.63086612 0.24809286 0.1355346
 0.37709609 0.97467192 0.73932369 0.2309209  0.5513733  0.13403562
 0.93218018 0.31015638 0.87876905 0.86862086 0.7772937  0.30145114
 0.57134601 0.50648736 0.12315012 0.10988559 0.43911229 0.16474964
 0.30982113 0.66946563 0.68375411 0.51745078 0.0091503  0.22321016
 0.42596367 0.19932575 0.96775212 0.9619245  0.80347321 0.84801992
 0.33713092 0.55653279 0.40850499 0.80601514 0.02453742 0.19764129
 0.61929792 0.50536189 0.32037504 0.8793745  0.35689089 0.81838094
 0.96471916 0.04362456 0.87142197 0.56514292 0.61768629 0.71804714
 0.51980145 0.91199208 0.3871362  0.14807976 0.23502521 0.08010464
 0.4121144  0.59849295 0.09304271 0.46043379 0.86046937 0.3869387
 0.39088851 0.62942485 0.59908418 0.09973516 0.27631975 0.434665

In [188]:
arr.mean()

np.float64(0.5035515960394455)

In [189]:
arr.min()

np.float64(0.004192619434147393)

In [190]:
arr.max()

np.float64(0.9863105234047078)

In [191]:
arr.std()

np.float64(0.2943193700874724)

In [193]:
arr = np.random.rand(3,4)
arr

array([[0.26938604, 0.60867494, 0.38292113, 0.93323932],
       [0.6056772 , 0.3406446 , 0.97258283, 0.9453173 ],
       [0.59158337, 0.91828966, 0.56232228, 0.63342497]])

In [194]:
arr = np.array([10, 20, 30, 40, 50])

In [242]:
np.random.choice(arr,3)

array([30, 10, 40])

In [243]:
arr = np.array([1, 2, 3, 4, 5])

In [253]:
np.random.choice(arr,10)

array([4, 4, 2, 1, 1, 1, 5, 1, 5, 5])

In [254]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [272]:
np.random.shuffle(arr)
arr

array([ 4,  5,  9,  1,  6,  2,  3,  8,  7, 10])

In [273]:
arr = np.array([50, 10, 80, 30, 20, 70])

In [274]:
np.sort(arr)

array([10, 20, 30, 50, 70, 80])

In [277]:
np.sort(arr)[::-1]

array([80, 70, 50, 30, 20, 10])

In [278]:
arr = np.array([50, 10, 80, 30, 20])

In [279]:
np.argsort(arr)

array([1, 4, 3, 0, 2])

In [280]:
names = np.array(["A", "B", "C", "D"])
marks = np.array([75, 92, 68, 88])

In [286]:
order = np.argsort(marks)
r = names[order]

In [287]:
r

array(['C', 'A', 'D', 'B'], dtype='<U1')

In [288]:
arr = np.array([10, 25, 40, 55, 70, 85])

In [290]:
np.where(arr>50)[0]

array([3, 4, 5])

In [291]:
arr = np.array([10, 20, 10, 30, 20, 40, 10, 30])

In [294]:
np.unique(arr)

array([10, 20, 30, 40])

In [295]:
values, counts = np.unique(arr, return_counts=True)

In [297]:
for value, count in zip(values, counts):
    print(value, "→", count)

10 → 3
20 → 2
30 → 2
40 → 1


In [298]:
arr = np.array([0, 10, 0, 20, 30, 0, 40])

In [300]:
np.count_nonzero(arr)

np.int64(4)

In [316]:
scores = np.array([45, 78, 92, 56, 88, 34, 76, 95, 61, 83])

In [310]:
h = np.sort(scores)[-3:][::-1]
h

array([95, 92, 88])

In [326]:
l = np.sort(scores)[:3]
l

array([34, 45, 56])

In [319]:
a = np.sort(scores)
a

array([34, 45, 56, 61, 76, 78, 83, 88, 92, 95])

In [322]:
hi = np.argsort(scores)[-1:][::-1]
hi

array([7])

In [325]:
j = scores[scores>75]
j

array([78, 92, 88, 76, 95, 83])

In [328]:
c = np.count_nonzero(scores>75)
c

np.int64(6)

In [329]:
students = np.array(["A", "B", "C", "D", "E", "F"])

marks = np.array([82, 67, 95, 74, 88, 91])

In [332]:
t = students[np.argmax(marks)]
t

np.str_('C')

In [340]:
t3  = students[np.argsort(marks)[-3:][::-1]]
t3

array(['C', 'F', 'E'], dtype='<U1')

In [343]:
sd = students[np.argsort(marks)[::-1]]
sd

array(['C', 'F', 'E', 'A', 'D', 'B'], dtype='<U1')

In [344]:
np.count_nonzero(marks >= 80)

np.int64(4)